- hosts: localhost
  tasks:
    - name: Install essential Utility Python packages via PIP
      ansible.builtin.pip:
        name:
          - jupyterlab
          - notebook
          - jupyterlab_execute_time
          - jupyterlab-notifications
          - jupyter-resource-usage
          - jupyterlab_theme_solarized_dark
          - llama-cpp-python
          - wheel

    - name: Install TensorFlow via PIP
      ansible.builtin.pip:
        name:
          - tensorflow

    - name: Install LiteRT via PIP
      ansible.builtin.pip:
        name:
          - ai-edge-litert

    - name: Install PyTorch via PIP
      ansible.builtin.pip:
        name:
          - torch
          - torchvision
          - torchaudio
